// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/gomr/v1/control.proto

package gomrv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkerState int32

const (
	WorkerState_WORKER_STATE_IDLE     WorkerState = 0
	WorkerState_WORKER_STATE_BUSY     WorkerState = 1
	WorkerState_WORKER_STATE_DRAINING WorkerState = 2
	WorkerState_WORKER_STATE_DEAD     WorkerState = 3
)

// Enum value maps for WorkerState.
var (
	WorkerState_name = map[int32]string{
		0: "WORKER_STATE_IDLE",
		1: "WORKER_STATE_BUSY",
		2: "WORKER_STATE_DRAINING",
		3: "WORKER_STATE_DEAD",
	}
	WorkerState_value = map[string]int32{
		"WORKER_STATE_IDLE":     0,
		"WORKER_STATE_BUSY":     1,
		"WORKER_STATE_DRAINING": 2,
		"WORKER_STATE_DEAD":     3,
	}
)

func (x WorkerState) Enum() *WorkerState {
	p := new(WorkerState)
	*p = x
	return p
}

func (x WorkerState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkerState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_gomr_v1_control_proto_enumTypes[0].Descriptor()
}

func (WorkerState) Type() protoreflect.EnumType {
	return &file_proto_gomr_v1_control_proto_enumTypes[0]
}

func (x WorkerState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkerState.Descriptor instead.
func (WorkerState) EnumDescriptor() ([]byte, []int) {
	return file_proto_gomr_v1_control_proto_rawDescGZIP(), []int{0}
}

type TaskPhase int32

const (
	TaskPhase_TASK_PHASE_MAP       TaskPhase = 0
	TaskPhase_TASK_PHASE_REDUCE    TaskPhase = 1
	TaskPhase_TASK_PHASE_PROMOTION TaskPhase = 2
)

// Enum value maps for TaskPhase.
var (
	TaskPhase_name = map[int32]string{
		0: "TASK_PHASE_MAP",
		1: "TASK_PHASE_REDUCE",
		2: "TASK_PHASE_PROMOTION",
	}
	TaskPhase_value = map[string]int32{
		"TASK_PHASE_MAP":       0,
		"TASK_PHASE_REDUCE":    1,
		"TASK_PHASE_PROMOTION": 2,
	}
)

func (x TaskPhase) Enum() *TaskPhase {
	p := new(TaskPhase)
	*p = x
	return p
}

func (x TaskPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_gomr_v1_control_proto_enumTypes[1].Descriptor()
}

func (TaskPhase) Type() protoreflect.EnumType {
	return &file_proto_gomr_v1_control_proto_enumTypes[1]
}

func (x TaskPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskPhase.Descriptor instead.
func (TaskPhase) EnumDescriptor() ([]byte, []int) {
	return file_proto_gomr_v1_control_proto_rawDescGZIP(), []int{1}
}

type TaskResultState int32

const (
	TaskResultState_TASK_RESULT_STATE_SUCCESS TaskResultState = 0
	TaskResultState_TASK_RESULT_STATE_FAILED  TaskResultState = 1
	TaskResultState_TASK_RESULT_STATE_ABORTED TaskResultState = 2
)

// Enum value maps for TaskResultState.
var (
	TaskResultState_name = map[int32]string{
		0: "TASK_RESULT_STATE_SUCCESS",
		1: "TASK_RESULT_STATE_FAILED",
		2: "TASK_RESULT_STATE_ABORTED",
	}
	TaskResultState_value = map[string]int32{
		"TASK_RESULT_STATE_SUCCESS": 0,
		"TASK_RESULT_STATE_FAILED":  1,
		"TASK_RESULT_STATE_ABORTED": 2,
	}
)

func (x TaskResultState) Enum() *TaskResultState {
	p := new(TaskResultState)
	*p = x
	return p
}

func (x TaskResultState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskResultState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_gomr_v1_control_proto_enumTypes[2].Descriptor()
}

func (TaskResultState) Type() protoreflect.EnumType {
	return &file_proto_gomr_v1_control_proto_enumTypes[2]
}

func (x TaskResultState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskResultState.Descriptor instead.
func (TaskResultState) EnumDescriptor() ([]byte, []int) {
	return file_proto_gomr_v1_control_proto_rawDescGZIP(), []int{2}
}

type RegisterWorkerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	HttpAddr      string                 `protobuf:"bytes,2,opt,name=http_addr,json=httpAddr,proto3" json:"http_addr,omitempty"`
	State         WorkerState            `protobuf:"varint,3,opt,name=state,proto3,enum=gomr.v1.WorkerState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWorkerRequest) Reset() {
	*x = RegisterWorkerRequest{}
	mi := &file_proto_gomr_v1_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerRequest) ProtoMessage() {}

func (x *RegisterWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gomr_v1_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerRequest.ProtoReflect.Descriptor instead.
func (*RegisterWorkerRequest) Descriptor() ([]byte, []int) {
	return file_proto_gomr_v1_control_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterWorkerRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RegisterWorkerRequest) GetHttpAddr() string {
	if x != nil {
		return x.HttpAddr
	}
	return ""
}

func (x *RegisterWorkerRequest) GetState() WorkerState {
	if x != nil {
		return x.State
	}
	return WorkerState_WORKER_STATE_IDLE
}

type RegisterWorkerResponse struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Accepted                 bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message                  string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	HeartbeatIntervalSeconds uint32                 `protobuf:"varint,3,opt,name=heartbeat_interval_seconds,json=heartbeatIntervalSeconds,proto3" json:"heartbeat_interval_seconds,omitempty"`
	WorkerTimeoutSeconds     uint32                 `protobuf:"varint,4,opt,name=worker_timeout_seconds,json=workerTimeoutSeconds,proto3" json:"worker_timeout_seconds,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *RegisterWorkerResponse) Reset() {
	*x = RegisterWorkerResponse{}
	mi := &file_proto_gomr_v1_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerResponse) ProtoMessage() {}

func (x *RegisterWorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gomr_v1_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerResponse.ProtoReflect.Descriptor instead.
func (*RegisterWorkerResponse) Descriptor() ([]byte, []int) {
	return file_proto_gomr_v1_control_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterWorkerResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RegisterWorkerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterWorkerResponse) GetHeartbeatIntervalSeconds() uint32 {
	if x != nil {
		return x.HeartbeatIntervalSeconds
	}
	return 0
}

func (x *RegisterWorkerResponse) GetWorkerTimeoutSeconds() uint32 {
	if x != nil {
		return x.WorkerTimeoutSeconds
	}
	return 0
}

type TaskRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Phase         TaskPhase              `protobuf:"varint,3,opt,name=phase,proto3,enum=gomr.v1.TaskPhase" json:"phase,omitempty"`
	AttemptId     string                 `protobuf:"bytes,4,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRef) Reset() {
	*x = TaskRef{}
	mi := &file_proto_gomr_v1_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRef) ProtoMessage() {}

func (x *TaskRef) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gomr_v1_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRef.ProtoReflect.Descriptor instead.
func (*TaskRef) Descriptor() ([]byte, []int) {
	return file_proto_gomr_v1_control_proto_rawDescGZIP(), []int{2}
}

func (x *TaskRef) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *TaskRef) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskRef) GetPhase() TaskPhase {
	if x != nil {
		return x.Phase
	}
	return TaskPhase_TASK_PHASE_MAP
}

func (x *TaskRef) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

type TaskResult struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Task         *TaskRef               `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	State        TaskResultState        `protobuf:"varint,2,opt,name=state,proto3,enum=gomr.v1.TaskResultState" json:"state,omitempty"`
	ErrorMessage string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Map tasks publish one intermediate file per reduce partition.
	PartitionUrls []string `protobuf:"bytes,4,rep,name=partition_urls,json=partitionUrls,proto3" json:"partition_urls,omitempty"`
	// Reduce and promotion tasks report their object storage output.
	OutputObject  string `protobuf:"bytes,5,opt,name=output_object,json=outputObject,proto3" json:"output_object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_proto_gomr_v1_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gomr_v1_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_proto_gomr_v1_control_proto_rawDescGZIP(), []int{3}
}

func (x *TaskResult) GetTask() *TaskRef {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *TaskResult) GetState() TaskResultState {
	if x != nil {
		return x.State
	}
	return TaskResultState_TASK_RESULT_STATE_SUCCESS
}

func (x *TaskResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TaskResult) GetPartitionUrls() []string {
	if x != nil {
		return x.PartitionUrls
	}
	return nil
}

func (x *TaskResult) GetOutputObject() string {
	if x != nil {
		return x.OutputObject
	}
	return ""
}

type HeartbeatRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	WorkerId string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	State    WorkerState            `protobuf:"varint,2,opt,name=state,proto3,enum=gomr.v1.WorkerState" json:"state,omitempty"`
	// Set when the worker is BUSY.
	CurrentTask *TaskRef `protobuf:"bytes,3,opt,name=current_task,json=currentTask,proto3" json:"current_task,omitempty"`
	// Set when the worker is reporting the outcome of its last task attempt.
	LastResult    *TaskResult `protobuf:"bytes,4,opt,name=last_result,json=lastResult,proto3" json:"last_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_gomr_v1_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gomr_v1_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_gomr_v1_control_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *HeartbeatRequest) GetState() WorkerState {
	if x != nil {
		return x.State
	}
	return WorkerState_WORKER_STATE_IDLE
}

func (x *HeartbeatRequest) GetCurrentTask() *TaskRef {
	if x != nil {
		return x.CurrentTask
	}
	return nil
}

func (x *HeartbeatRequest) GetLastResult() *TaskResult {
	if x != nil {
		return x.LastResult
	}
	return nil
}

type MapAssignment struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	JobId            string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	TaskId           string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	InputUri         string                 `protobuf:"bytes,3,opt,name=input_uri,json=inputUri,proto3" json:"input_uri,omitempty"`
	MapSourceUri     string                 `protobuf:"bytes,4,opt,name=map_source_uri,json=mapSourceUri,proto3" json:"map_source_uri,omitempty"`
	MapCompileCmd    string                 `protobuf:"bytes,5,opt,name=map_compile_cmd,json=mapCompileCmd,proto3" json:"map_compile_cmd,omitempty"`
	ReducePartitions uint32                 `protobuf:"varint,6,opt,name=reduce_partitions,json=reducePartitions,proto3" json:"reduce_partitions,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MapAssignment) Reset() {
	*x = MapAssignment{}
	mi := &file_proto_gomr_v1_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapAssignment) ProtoMessage() {}

func (x *MapAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gomr_v1_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapAssignment.ProtoReflect.Descriptor instead.
func (*MapAssignment) Descriptor() ([]byte, []int) {
	return file_proto_gomr_v1_control_proto_rawDescGZIP(), []int{5}
}

func (x *MapAssignment) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *MapAssignment) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *MapAssignment) GetInputUri() string {
	if x != nil {
		return x.InputUri
	}
	return ""
}

func (x *MapAssignment) GetMapSourceUri() string {
	if x != nil {
		return x.MapSourceUri
	}
	return ""
}

func (x *MapAssignment) GetMapCompileCmd() string {
	if x != nil {
		return x.MapCompileCmd
	}
	return ""
}

func (x *MapAssignment) GetReducePartitions() uint32 {
	if x != nil {
		return x.ReducePartitions
	}
	return 0
}

type ReduceAssignment struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	JobId            string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	TaskId           string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Partition        uint32                 `protobuf:"varint,3,opt,name=partition,proto3" json:"partition,omitempty"`
	ReduceSourceUri  string                 `protobuf:"bytes,4,opt,name=reduce_source_uri,json=reduceSourceUri,proto3" json:"reduce_source_uri,omitempty"`
	ReduceCompileCmd string                 `protobuf:"bytes,5,opt,name=reduce_compile_cmd,json=reduceCompileCmd,proto3" json:"reduce_compile_cmd,omitempty"`
	InputUrls        []string               `protobuf:"bytes,6,rep,name=input_urls,json=inputUrls,proto3" json:"input_urls,omitempty"`
	OutputPrefix     string                 `protobuf:"bytes,7,opt,name=output_prefix,json=outputPrefix,proto3" json:"output_prefix,omitempty"`
	AllMapsComplete  bool                   `protobuf:"varint,8,opt,name=all_maps_complete,json=allMapsComplete,proto3" json:"all_maps_complete,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReduceAssignment) Reset() {
	*x = ReduceAssignment{}
	mi := &file_proto_gomr_v1_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReduceAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReduceAssignment) ProtoMessage() {}

func (x *ReduceAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gomr_v1_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReduceAssignment.ProtoReflect.Descriptor instead.
func (*ReduceAssignment) Descriptor() ([]byte, []int) {
	return file_proto_gomr_v1_control_proto_rawDescGZIP(), []int{6}
}

func (x *ReduceAssignment) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ReduceAssignment) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ReduceAssignment) GetPartition() uint32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *ReduceAssignment) GetReduceSourceUri() string {
	if x != nil {
		return x.ReduceSourceUri
	}
	return ""
}

func (x *ReduceAssignment) GetReduceCompileCmd() string {
	if x != nil {
		return x.ReduceCompileCmd
	}
	return ""
}

func (x *ReduceAssignment) GetInputUrls() []string {
	if x != nil {
		return x.InputUrls
	}
	return nil
}

func (x *ReduceAssignment) GetOutputPrefix() string {
	if x != nil {
		return x.OutputPrefix
	}
	return ""
}

func (x *ReduceAssignment) GetAllMapsComplete() bool {
	if x != nil {
		return x.AllMapsComplete
	}
	return false
}

type PromotionAssignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	AttemptId     string                 `protobuf:"bytes,3,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	TempObject    string                 `protobuf:"bytes,4,opt,name=temp_object,json=tempObject,proto3" json:"temp_object,omitempty"`
	FinalObject   string                 `protobuf:"bytes,5,opt,name=final_object,json=finalObject,proto3" json:"final_object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromotionAssignment) Reset() {
	*x = PromotionAssignment{}
	mi := &file_proto_gomr_v1_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromotionAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromotionAssignment) ProtoMessage() {}

func (x *PromotionAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gomr_v1_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromotionAssignment.ProtoReflect.Descriptor instead.
func (*PromotionAssignment) Descriptor() ([]byte, []int) {
	return file_proto_gomr_v1_control_proto_rawDescGZIP(), []int{7}
}

func (x *PromotionAssignment) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *PromotionAssignment) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *PromotionAssignment) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *PromotionAssignment) GetTempObject() string {
	if x != nil {
		return x.TempObject
	}
	return ""
}

func (x *PromotionAssignment) GetFinalObject() string {
	if x != nil {
		return x.FinalObject
	}
	return ""
}

type Assignment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Assignment_Map
	//	*Assignment_Reduce
	//	*Assignment_Promotion
	Kind          isAssignment_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Assignment) Reset() {
	*x = Assignment{}
	mi := &file_proto_gomr_v1_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Assignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assignment) ProtoMessage() {}

func (x *Assignment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gomr_v1_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assignment.ProtoReflect.Descriptor instead.
func (*Assignment) Descriptor() ([]byte, []int) {
	return file_proto_gomr_v1_control_proto_rawDescGZIP(), []int{8}
}

func (x *Assignment) GetKind() isAssignment_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Assignment) GetMap() *MapAssignment {
	if x != nil {
		if x, ok := x.Kind.(*Assignment_Map); ok {
			return x.Map
		}
	}
	return nil
}

func (x *Assignment) GetReduce() *ReduceAssignment {
	if x != nil {
		if x, ok := x.Kind.(*Assignment_Reduce); ok {
			return x.Reduce
		}
	}
	return nil
}

func (x *Assignment) GetPromotion() *PromotionAssignment {
	if x != nil {
		if x, ok := x.Kind.(*Assignment_Promotion); ok {
			return x.Promotion
		}
	}
	return nil
}

type isAssignment_Kind interface {
	isAssignment_Kind()
}

type Assignment_Map struct {
	Map *MapAssignment `protobuf:"bytes,1,opt,name=map,proto3,oneof"`
}

type Assignment_Reduce struct {
	Reduce *ReduceAssignment `protobuf:"bytes,2,opt,name=reduce,proto3,oneof"`
}

type Assignment_Promotion struct {
	Promotion *PromotionAssignment `protobuf:"bytes,3,opt,name=promotion,proto3,oneof"`
}

func (*Assignment_Map) isAssignment_Kind() {}

func (*Assignment_Reduce) isAssignment_Kind() {}

func (*Assignment_Promotion) isAssignment_Kind() {}

type HeartbeatResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ShouldAbortCurrentTask bool                   `protobuf:"varint,1,opt,name=should_abort_current_task,json=shouldAbortCurrentTask,proto3" json:"should_abort_current_task,omitempty"`
	Assignment             *Assignment            `protobuf:"bytes,2,opt,name=assignment,proto3" json:"assignment,omitempty"`
	AdditionalReduceUrls   []string               `protobuf:"bytes,3,rep,name=additional_reduce_urls,json=additionalReduceUrls,proto3" json:"additional_reduce_urls,omitempty"`
	AllMapsComplete        bool                   `protobuf:"varint,4,opt,name=all_maps_complete,json=allMapsComplete,proto3" json:"all_maps_complete,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_gomr_v1_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gomr_v1_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_gomr_v1_control_proto_rawDescGZIP(), []int{9}
}

func (x *HeartbeatResponse) GetShouldAbortCurrentTask() bool {
	if x != nil {
		return x.ShouldAbortCurrentTask
	}
	return false
}

func (x *HeartbeatResponse) GetAssignment() *Assignment {
	if x != nil {
		return x.Assignment
	}
	return nil
}

func (x *HeartbeatResponse) GetAdditionalReduceUrls() []string {
	if x != nil {
		return x.AdditionalReduceUrls
	}
	return nil
}

func (x *HeartbeatResponse) GetAllMapsComplete() bool {
	if x != nil {
		return x.AllMapsComplete
	}
	return false
}

var File_proto_gomr_v1_control_proto protoreflect.FileDescriptor

const file_proto_gomr_v1_control_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/gomr/v1/control.proto\x12\agomr.v1\"}\n" +
	"\x15RegisterWorkerRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1b\n" +
	"\thttp_addr\x18\x02 \x01(\tR\bhttpAddr\x12*\n" +
	"\x05state\x18\x03 \x01(\x0e2\x14.gomr.v1.WorkerStateR\x05state\"\xc2\x01\n" +
	"\x16RegisterWorkerResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12<\n" +
	"\x1aheartbeat_interval_seconds\x18\x03 \x01(\rR\x18heartbeatIntervalSeconds\x124\n" +
	"\x16worker_timeout_seconds\x18\x04 \x01(\rR\x14workerTimeoutSeconds\"\x82\x01\n" +
	"\aTaskRef\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12(\n" +
	"\x05phase\x18\x03 \x01(\x0e2\x12.gomr.v1.TaskPhaseR\x05phase\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x04 \x01(\tR\tattemptId\"\xd3\x01\n" +
	"\n" +
	"TaskResult\x12$\n" +
	"\x04task\x18\x01 \x01(\v2\x10.gomr.v1.TaskRefR\x04task\x12.\n" +
	"\x05state\x18\x02 \x01(\x0e2\x18.gomr.v1.TaskResultStateR\x05state\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12%\n" +
	"\x0epartition_urls\x18\x04 \x03(\tR\rpartitionUrls\x12#\n" +
	"\routput_object\x18\x05 \x01(\tR\foutputObject\"\xc6\x01\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12*\n" +
	"\x05state\x18\x02 \x01(\x0e2\x14.gomr.v1.WorkerStateR\x05state\x123\n" +
	"\fcurrent_task\x18\x03 \x01(\v2\x10.gomr.v1.TaskRefR\vcurrentTask\x124\n" +
	"\vlast_result\x18\x04 \x01(\v2\x13.gomr.v1.TaskResultR\n" +
	"lastResult\"\xd7\x01\n" +
	"\rMapAssignment\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x1b\n" +
	"\tinput_uri\x18\x03 \x01(\tR\binputUri\x12$\n" +
	"\x0emap_source_uri\x18\x04 \x01(\tR\fmapSourceUri\x12&\n" +
	"\x0fmap_compile_cmd\x18\x05 \x01(\tR\rmapCompileCmd\x12+\n" +
	"\x11reduce_partitions\x18\x06 \x01(\rR\x10reducePartitions\"\xaa\x02\n" +
	"\x10ReduceAssignment\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x1c\n" +
	"\tpartition\x18\x03 \x01(\rR\tpartition\x12*\n" +
	"\x11reduce_source_uri\x18\x04 \x01(\tR\x0freduceSourceUri\x12,\n" +
	"\x12reduce_compile_cmd\x18\x05 \x01(\tR\x10reduceCompileCmd\x12\x1d\n" +
	"\n" +
	"input_urls\x18\x06 \x03(\tR\tinputUrls\x12#\n" +
	"\routput_prefix\x18\a \x01(\tR\foutputPrefix\x12*\n" +
	"\x11all_maps_complete\x18\b \x01(\bR\x0fallMapsComplete\"\xa8\x01\n" +
	"\x13PromotionAssignment\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x03 \x01(\tR\tattemptId\x12\x1f\n" +
	"\vtemp_object\x18\x04 \x01(\tR\n" +
	"tempObject\x12!\n" +
	"\ffinal_object\x18\x05 \x01(\tR\vfinalObject\"\xb3\x01\n" +
	"\n" +
	"Assignment\x12*\n" +
	"\x03map\x18\x01 \x01(\v2\x16.gomr.v1.MapAssignmentH\x00R\x03map\x123\n" +
	"\x06reduce\x18\x02 \x01(\v2\x19.gomr.v1.ReduceAssignmentH\x00R\x06reduce\x12<\n" +
	"\tpromotion\x18\x03 \x01(\v2\x1c.gomr.v1.PromotionAssignmentH\x00R\tpromotionB\x06\n" +
	"\x04kind\"\xe5\x01\n" +
	"\x11HeartbeatResponse\x129\n" +
	"\x19should_abort_current_task\x18\x01 \x01(\bR\x16shouldAbortCurrentTask\x123\n" +
	"\n" +
	"assignment\x18\x02 \x01(\v2\x13.gomr.v1.AssignmentR\n" +
	"assignment\x124\n" +
	"\x16additional_reduce_urls\x18\x03 \x03(\tR\x14additionalReduceUrls\x12*\n" +
	"\x11all_maps_complete\x18\x04 \x01(\bR\x0fallMapsComplete*m\n" +
	"\vWorkerState\x12\x15\n" +
	"\x11WORKER_STATE_IDLE\x10\x00\x12\x15\n" +
	"\x11WORKER_STATE_BUSY\x10\x01\x12\x19\n" +
	"\x15WORKER_STATE_DRAINING\x10\x02\x12\x15\n" +
	"\x11WORKER_STATE_DEAD\x10\x03*P\n" +
	"\tTaskPhase\x12\x12\n" +
	"\x0eTASK_PHASE_MAP\x10\x00\x12\x15\n" +
	"\x11TASK_PHASE_REDUCE\x10\x01\x12\x18\n" +
	"\x14TASK_PHASE_PROMOTION\x10\x02*m\n" +
	"\x0fTaskResultState\x12\x1d\n" +
	"\x19TASK_RESULT_STATE_SUCCESS\x10\x00\x12\x1c\n" +
	"\x18TASK_RESULT_STATE_FAILED\x10\x01\x12\x1d\n" +
	"\x19TASK_RESULT_STATE_ABORTED\x10\x022\xa6\x01\n" +
	"\rMasterService\x12Q\n" +
	"\x0eRegisterWorker\x12\x1e.gomr.v1.RegisterWorkerRequest\x1a\x1f.gomr.v1.RegisterWorkerResponse\x12B\n" +
	"\tHeartbeat\x12\x19.gomr.v1.HeartbeatRequest\x1a\x1a.gomr.v1.HeartbeatResponseB/Z-github.com/sophic00/gomr/proto/gomr/v1;gomrv1b\x06proto3"

var (
	file_proto_gomr_v1_control_proto_rawDescOnce sync.Once
	file_proto_gomr_v1_control_proto_rawDescData []byte
)

func file_proto_gomr_v1_control_proto_rawDescGZIP() []byte {
	file_proto_gomr_v1_control_proto_rawDescOnce.Do(func() {
		file_proto_gomr_v1_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gomr_v1_control_proto_rawDesc), len(file_proto_gomr_v1_control_proto_rawDesc)))
	})
	return file_proto_gomr_v1_control_proto_rawDescData
}

var file_proto_gomr_v1_control_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_gomr_v1_control_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_gomr_v1_control_proto_goTypes = []any{
	(WorkerState)(0),               // 0: gomr.v1.WorkerState
	(TaskPhase)(0),                 // 1: gomr.v1.TaskPhase
	(TaskResultState)(0),           // 2: gomr.v1.TaskResultState
	(*RegisterWorkerRequest)(nil),  // 3: gomr.v1.RegisterWorkerRequest
	(*RegisterWorkerResponse)(nil), // 4: gomr.v1.RegisterWorkerResponse
	(*TaskRef)(nil),                // 5: gomr.v1.TaskRef
	(*TaskResult)(nil),             // 6: gomr.v1.TaskResult
	(*HeartbeatRequest)(nil),       // 7: gomr.v1.HeartbeatRequest
	(*MapAssignment)(nil),          // 8: gomr.v1.MapAssignment
	(*ReduceAssignment)(nil),       // 9: gomr.v1.ReduceAssignment
	(*PromotionAssignment)(nil),    // 10: gomr.v1.PromotionAssignment
	(*Assignment)(nil),             // 11: gomr.v1.Assignment
	(*HeartbeatResponse)(nil),      // 12: gomr.v1.HeartbeatResponse
}
var file_proto_gomr_v1_control_proto_depIdxs = []int32{
	0,  // 0: gomr.v1.RegisterWorkerRequest.state:type_name -> gomr.v1.WorkerState
	1,  // 1: gomr.v1.TaskRef.phase:type_name -> gomr.v1.TaskPhase
	5,  // 2: gomr.v1.TaskResult.task:type_name -> gomr.v1.TaskRef
	2,  // 3: gomr.v1.TaskResult.state:type_name -> gomr.v1.TaskResultState
	0,  // 4: gomr.v1.HeartbeatRequest.state:type_name -> gomr.v1.WorkerState
	5,  // 5: gomr.v1.HeartbeatRequest.current_task:type_name -> gomr.v1.TaskRef
	6,  // 6: gomr.v1.HeartbeatRequest.last_result:type_name -> gomr.v1.TaskResult
	8,  // 7: gomr.v1.Assignment.map:type_name -> gomr.v1.MapAssignment
	9,  // 8: gomr.v1.Assignment.reduce:type_name -> gomr.v1.ReduceAssignment
	10, // 9: gomr.v1.Assignment.promotion:type_name -> gomr.v1.PromotionAssignment
	11, // 10: gomr.v1.HeartbeatResponse.assignment:type_name -> gomr.v1.Assignment
	3,  // 11: gomr.v1.MasterService.RegisterWorker:input_type -> gomr.v1.RegisterWorkerRequest
	7,  // 12: gomr.v1.MasterService.Heartbeat:input_type -> gomr.v1.HeartbeatRequest
	4,  // 13: gomr.v1.MasterService.RegisterWorker:output_type -> gomr.v1.RegisterWorkerResponse
	12, // 14: gomr.v1.MasterService.Heartbeat:output_type -> gomr.v1.HeartbeatResponse
	13, // [13:15] is the sub-list for method output_type
	11, // [11:13] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_gomr_v1_control_proto_init() }
func file_proto_gomr_v1_control_proto_init() {
	if File_proto_gomr_v1_control_proto != nil {
		return
	}
	file_proto_gomr_v1_control_proto_msgTypes[8].OneofWrappers = []any{
		(*Assignment_Map)(nil),
		(*Assignment_Reduce)(nil),
		(*Assignment_Promotion)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gomr_v1_control_proto_rawDesc), len(file_proto_gomr_v1_control_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gomr_v1_control_proto_goTypes,
		DependencyIndexes: file_proto_gomr_v1_control_proto_depIdxs,
		EnumInfos:         file_proto_gomr_v1_control_proto_enumTypes,
		MessageInfos:      file_proto_gomr_v1_control_proto_msgTypes,
	}.Build()
	File_proto_gomr_v1_control_proto = out.File
	file_proto_gomr_v1_control_proto_goTypes = nil
	file_proto_gomr_v1_control_proto_depIdxs = nil
}
